//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuoteApplication_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int QuoteNumber { get; set; }
        public System.DateTime QuoteGenerationDate { get; set; }
        public int InsureeID { get; set; }
        public decimal BaseRate { get; set; }
        public decimal AgeUnder18Rate { get; set; }
        public decimal AgeBetween18And25Rate { get; set; }
        public decimal AgeOver25Rate { get; set; }
        public decimal AutoYearBefore2000Rate { get; set; }
        public decimal AutoYearBetween2000And2015Rate { get; set; }
        public decimal AutoYearAfter2015Rate { get; set; }
        public decimal MakeIsPorscheRate { get; set; }
        public decimal ModelIsCarreraRate { get; set; }
        public decimal SpeedingTicketRate { get; set; }
        public decimal SubtotalAfterSpeedingTicketRateCalculation { get; set; }
        public decimal DUIIncreaseOf25PercentRate { get; set; }
        public decimal SubtotalAfterDUIRateCalculation { get; set; }
        public decimal FullCoverageInsuranceRate { get; set; }
        public decimal QuoteRateTotalAfterCalculation { get; set; }
        public decimal FinalQuoteYearly_1PaymentDiscountApplied { get; set; }
        public decimal FinalQuoteMonthly_12PaymentsNoDiscount { get; set; }
        public decimal DiscountAmountForPaymentInFull { get; set; }
    
        public virtual Insuree Insuree { get; set; }
    }
}
